# Generated by Django 5.0.6 on 2024-06-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='member',
            new_name='group',
        ),
    ]
